import type { CollectionCreateSchema } from "typesense/lib/Typesense/Collections";

/**
 * Returns the Typesense collection schema for the departures collection.
 * This was exported from Typesense; adapted to a TypeScript module and
 * patched so that `productId` is facetable (facet: true) to allow grouping.
 */
export function getTripCollectionSchema(): CollectionCreateSchema {
  return {
    created_at: 1777530511,
    curation_sets: [],
    default_sorting_field: "",
    enable_nested_fields: true,
    fields: [
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: ".*",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "auto",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "field",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "_geoloc",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "object[]",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "activities",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string[]",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "closedForBooking",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "departureId",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "destinations",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string[]",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "duration",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "endCity",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "endDate",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "hasPlacesLeft",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "location_facet",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "float[]",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "locations",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string[]",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "object",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "map",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "object",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "marketingRating",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: true,
        index: true,
        infix: false,
        locale: "",
        name: "marketingRegions",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string[]",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "name",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "physicalRating",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "placesLeft",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "primaryCountry",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "productCode",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: true,
        index: true,
        infix: false,
        locale: "",
        name: "productId",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "productImages",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "object[]",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "productUrl",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "regions",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string[]",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "reviewCount",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "reviewRating",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "float",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "startCity",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "startDate",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: true,
        index: true,
        infix: false,
        locale: "",
        name: "styles",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string[]",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "subdivisionCountries",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string[]",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "subdivisions",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string[]",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "themes",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string[]",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "map.width",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "map.url",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "map.height",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "_geoloc.lat",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "float[]",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.zar.type",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.zar.onSale",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.zar.isHighlightedPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.zar.isHighlightedDeal",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.zar.discountPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.zar.depositAmount",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.chf.onSale",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.chf.isHighlightedPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.usd.isHighlightedPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.chf.isHighlightedDeal",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.chf.depositAmount",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.eur.price",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.gbp.depositAmount",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "productImages.alt",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string[]",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "productImages.url",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string[]",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.cad.currencyCode",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.aud.onSale",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.cad.isHighlightedDeal",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.eur.discountPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.gbp.discountPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.aud.isHighlightedDeal",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "map.title",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.cad.discountPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.chf.discountPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.cad.onSale",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "_geoloc.lng",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "float[]",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.nzd.isHighlightedPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.usd.currencyCode",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.eur.currencyCode",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.cad.isHighlightedPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.aud.currencyCode",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.eur.type",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.eur.depositAmount",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.aud.isHighlightedPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.aud.price",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.nzd.type",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.chf.price",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.zar.price",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.aud.discountPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "map.alt",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.chf.type",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.chf.currencyCode",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.cad.price",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.cad.type",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.gbp.isHighlightedPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.usd.depositAmount",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.aud.type",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.nzd.discountPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.nzd.onSale",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.cad.depositAmount",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.eur.isHighlightedDeal",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.usd.isHighlightedDeal",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.eur.isHighlightedPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.eur.onSale",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.gbp.price",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.nzd.currencyCode",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.gbp.currencyCode",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.aud.depositAmount",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.gbp.isHighlightedDeal",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.gbp.onSale",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.gbp.type",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.usd.discountPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.usd.price",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.nzd.depositAmount",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.nzd.isHighlightedDeal",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.zar.currencyCode",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.nzd.price",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.usd.onSale",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "bool",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.usd.type",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "_collections",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string[]",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "tags",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string[]",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.zar.childDiscountPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.chf.childPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.chf.childDiscountPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.usd.childPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.zar.childPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.aud.childDiscountPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.gbp.childDiscountPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.aud.childPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.cad.childPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.usd.childDiscountPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.cad.childDiscountPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.eur.childDiscountPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.gbp.childPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.nzd.childDiscountPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.eur.childPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.nzd.childPrice",
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "int64",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.cad.promotionName",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: "",
        name: "lowestPrice.usd.promotionName",
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: "",
        store: true,
        truncate_len: 100,
        type: "string",
      },
    ],
    name: "dev_intrepid_departure",
    num_documents: 1000,
    symbols_to_index: [],
    synonym_sets: [],
    token_separators: [],
  } as CollectionCreateSchema;
}

export default getTripCollectionSchema;
