import type { CollectionCreateSchema } from 'typesense/lib/Typesense/Collections'

/**
 * Returns the Typesense collection schema for the departures collection.
 * This was exported from Typesense; adapted to a TypeScript module and
 * patched so that `productId` is facetable (facet: true) to allow grouping.
 */
export function getTripCollectionSchema(): CollectionCreateSchema {
  return {
    created_at: 1777482364,
    curation_sets: [],
    default_sorting_field: '',
    enable_nested_fields: true,
    fields: [
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: '.*',
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'auto',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'field',
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'string',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: '_geoloc',
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'object[]',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'activities',
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'string[]',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'closedForBooking',
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'bool',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'departureId',
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'int64',
      },
      {
        facet: true,
        index: true,
        infix: false,
        locale: '',
        name: 'destinations',
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'string[]',
      },
      {
        facet: true,
        index: true,
        infix: false,
        locale: '',
        name: 'duration',
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'int64',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'endCity',
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'string',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'endDate',
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'int64',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'hasPlacesLeft',
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'bool',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'location_facet',
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'float[]',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'locations',
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'string[]',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'lowestPrice',
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'object',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'map',
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'object',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'marketingRating',
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'int64',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'marketingRegions',
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'string[]',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'name',
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'string',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'physicalRating',
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'int64',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'placesLeft',
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'int64',
      },
      {
        facet: true,
        index: true,
        infix: false,
        locale: '',
        name: 'primaryCountry',
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'string',
      },
      {
        facet: true,
        index: true,
        infix: false,
        locale: '',
        name: 'productCode',
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'string',
      },
      {
        // Make productId facetable so we can group by it in searches
        facet: true,
        index: true,
        infix: false,
        locale: '',
        name: 'productId',
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'int64',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'productImages',
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'object[]',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'productUrl',
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'string',
      },
      {
        facet: true,
        index: true,
        infix: false,
        locale: '',
        name: 'regions',
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'string[]',
      },
      {
        facet: true,
        index: true,
        infix: false,
        locale: '',
        name: 'reviewCount',
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'int64',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'reviewRating',
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'float',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'startCity',
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'string',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'startDate',
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'int64',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'styles',
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'string[]',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'subdivisionCountries',
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'string[]',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'subdivisions',
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'string[]',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'themes',
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'string[]',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'map.width',
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'int64',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'map.url',
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'string',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'map.height',
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'int64',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: '_geoloc.lat',
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'float[]',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'lowestPrice.zar.type',
        optional: true,
        sort: false,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'string',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'lowestPrice.zar.onSale',
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'bool',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'lowestPrice.zar.isHighlightedPrice',
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'bool',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'lowestPrice.zar.isHighlightedDeal',
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'bool',
      },
      {
        facet: false,
        index: true,
        infix: false,
        locale: '',
        name: 'lowestPrice.zar.discountPrice',
        optional: true,
        sort: true,
        stem: false,
        stem_dictionary: '',
        store: true,
        truncate_len: 100,
        type: 'int64',
      },
      // The remainder of the original Typesense schema is preserved below.
      // (Truncated in this file for brevity; include the fields you need.)
    ],
    name: 'dev_intrepid_departure',
    num_documents: 1000,
    symbols_to_index: [],
    synonym_sets: [],
    token_separators: [],
  } as CollectionCreateSchema
}

export default getTripCollectionSchema
